spring.application.name=students


//spring.datasource.driver-class-name=org.postgresql.Driver........maybe just keep these 4 lines for reference
//spring.datasource.url=jdbc:postgresql://localhost:5432/demo
//spring.datasource.username=postgres
//spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=richard
spring.security.user.password=akkad



spring.jpa.hibernate.ddl-auto=update


cloud.aws.credentials.access-key=AKIAZ5QOPESYD75EBHJE
cloud.aws.credentials.secret-key=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


cloud.aws.region.static=eu-north-1
aws.bucket.name=studentpartimespringbootwebsite


spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://database-1.craa4q0o20rf.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sunshine!1981


server.port=5000